version: "3.8"

services:
  backend:
    stdin_open: true
    build: ./backend
    ports:
      - "3001:3001"
    command: npm start
  client:
    stdin_open: true
    build: ./frontend
    ports:
      - "3000:3000"
    command: npm start
