version: 2.1
executorType: machine
jobs:
  backend_build:
    working_directory: ~/backend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: docker backend
          command: docker build
  frontend_build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: docker frontend
          command: docker build

workflows:
  version: 2

  my_workflow:
    jobs:
      - backend_build
      - frontend_build:
          requires:
            - backend_build
