version: 2.1
executorType: machine
jobs:
  backend_build:
    working_directory: ~/backend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run:
          name: Docker build backend
          command: docker-compose -f

  frontend_build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run:
          name: Docker build frontend
          command: docker-compose -f

workflows:
  version: 2

  my_workflow:
    jobs:
      - backend_build
      - frontend_build:
          requires:
            - backend_build
