version: 2.1
executorType: machine
jobs:
  backend_build:
    working_directory: ./backend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Docker build backend
          command: docker build -t over-the-line_backend_1:latest

  frontend_build:
    working_directory: ./frontend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Docker build frontend
          command: docker build -t over-the-line_client_1:latest .

workflows:
  version: 2

  my_workflow:
    jobs:
      - backend_build
      - frontend_build:
          requires:
            - backend_build
