version: 2.1
executorType: machine
jobs:
  backend_build:
    docker:
      - image: circleci/node:latest
    working_directory: ~./backend
    steps:
      - checkout
      - run:
          name: docker backend
          command: docker-compose up
  frontend_build:
    docker:
      - image: circleci/node:latest
    working_directory: ~./frontend/
    steps:
      - checkout
      - run:
          name: docker frontend
          command: docker-compose up

workflows:
  version: 2.1

  my_workflow:
    jobs:
      - backend_build
      - frontend_build:
          requires:
            - backend_build
