version: 2.1
executorType: machine
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: docker build
          command: docker-compose up

workflows:
  version: 2

  my_workflow:
    jobs:
      - build
